# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [2.7]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Clone and checkout
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Get matching python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Build with python version from the matrix
    - name: Build with python ${{ matrix.python-version }}
      run: python${{ matrix.python-version }} mbs/mbs

    - uses: actions/upload-artifact@v2
      with:
        name: hboot_image_compiler
        path: targets/repository/org/muhkuh/tools/hboot_image_compiler/**/hboot_image_compiler-*.zip
